# Generated by Django 2.1.5 on 2020-06-15 23:05

from django.db import migrations, models
import podverse_db.models.podcast


class Migration(migrations.Migration):

    dependencies = [
        ('podverse_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.CharField(default=podverse_db.models.podcast.Podcast.shortid, max_length=14, primary_key=True, serialize=False),
        ),
    ]
