# Generated by Django 2.2.13 on 2020-10-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podverse_db', '0002_auto_20200615_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='feedLastParseFailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcastIndexId',
            field=models.CharField(blank=True, max_length=2084),
        ),
    ]
