# Generated by Django 2.2.2 on 2019-06-10 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('episodeType', models.CharField(blank=True, max_length=2084)),
                ('guid', models.CharField(blank=True, max_length=2084)),
                ('imageUrl', models.URLField(blank=True)),
                ('isExplicit', models.BooleanField()),
                ('isPublic', models.BooleanField()),
                ('linkUrl', models.URLField(blank=True)),
                ('mediaFilesize', models.PositiveIntegerField(default=0)),
                ('mediaType', models.CharField(blank=True, max_length=2084)),
                ('meidaUrl', models.URLField(unique=True)),
                ('pastHourTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Hour')),
                ('pastDayTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Day')),
                ('pastWeekTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Week')),
                ('pastMonthTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Month')),
                ('pastYearTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Year')),
                ('pastAllTimeTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - All Time')),
                ('pubDate', models.DateTimeField(blank=True)),
                ('title', models.CharField(blank=True, max_length=2084)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episodes',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('feedLastUpdated', models.DateTimeField(blank=True)),
                ('guid', models.CharField(blank=True, max_length=2084)),
                ('imageUrl', models.URLField(blank=True)),
                ('isExplicit', models.BooleanField()),
                ('isPublic', models.BooleanField()),
                ('language', models.CharField(blank=True, max_length=2084)),
                ('lastEpisodePubDate', models.DateTimeField(blank=True)),
                ('lastEpisodeTitle', models.CharField(blank=True, max_length=2084)),
                ('linkUrl', models.URLField(blank=True)),
                ('pastHourTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Hour')),
                ('pastDayTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Day')),
                ('pastWeekTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Week')),
                ('pastMonthTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Month')),
                ('pastYearTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - Past Year')),
                ('pastAllTimeTotalUniquePageviews', models.PositiveIntegerField(default=0, verbose_name='Pageviews - All Time')),
                ('priority', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sortableTitle', models.CharField(blank=True, max_length=2084)),
                ('title', models.CharField(blank=True, max_length=2084)),
                ('type', models.CharField(blank=True, max_length=2084)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'podcasts',
            },
        ),
    ]
